Regrab any previous gui focus after closing console.
limbonaut/limbo_console pull request #5
Opened 2024-11-22 11:32 UTC by Wierdox

For me at least this is important, I have logic that assumes there is always a focused UI element in some menus. I imagine in most cases this is fine to do, but maybe it should be a toggleable option?

Also just to let you know, I have another PR to add animated console opening/closing, but I'll wait for my PRs to be OKed or not first since it would touch some of the same code.

2024-11-22 12:04 UTC, limbonaut requested changes

2024-11-22 12:04 UTC, limbonaut commented on limbo_console.gd
> +		if _previous_gui_focus:
Need to use `is_instace_valid()` because a control may be removed as an effect of a command

2024-11-22 12:07 UTC, limbonaut commented
> For me at least this is important, I have logic that assumes there is always a focused UI element in some menus. I imagine in most cases this is fine to do, but maybe it should be a toggleable option?

I agree, this is fine. No need for an option until proven problematic.

2024-11-22 22:26 UTC, Wierdox commented
Okay, added your suggestions and I also rebased this off of #4, so if you merge them in order it should be clean. Or so I think, I'm not well versed in that area.

2024-11-23 13:30 UTC, limbonaut approved these changes
Looks good. GitHub's **Files Changed** panel is confused, showing previous PR changes as well. But I think it'll merge just fine.
Thanks.

2024-11-23 13:30 UTC, merged